server:
  port: 8301
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud
    username: root
    password: root
  # 应用名称
  application:
    name: borrowservice
#  session:
#    # 存储类型修改为redis
#    store-type: redis
#  redis:
#    # Redis服务器的信息
#    host: localhost
  cloud:
    nacos:
      discovery:
        #配置nacos注册中心地址
        server-addr: localhost:8848
        # 组别
        group: DEFAULT_GROUP
        # 临时实例true-临时 false-非临时
        #ephemeral: false
    loadbalancer:
      nacos:
        #开启集群区域优先访问
        enabled: true
    sentinel:
      transport:
        # 添加监控页面地址即可
        dashboard: localhost:8858
      # 关闭Context收敛，这样被监控方法可以进行不同链路的单独控制
      web-context-unify: false
      # 将刚刚编写的请求映射设定为限流页面
      block-page: /blocked
feign:
  sentinel:
    # 让feign支持sentinel的熔断降级
    enabled: true
seata:
  registry:
    type: nacos
    nacos:
      application: seata-server
      group: DEFAULT_GROUP
      server-addr: localhost:8848
      namespace: seata
  service:
    vgroup-mapping:
      default_tx_group: default
  #      bookservice_tx_group: default
  #  tx-service-group: 'bookservice_tx_group'
  config:
    type: nacos
    nacos:
      application: seata-server
      group: DEFAULT_GROUP
      server-addr: localhost:8848
      namespace: seata
      data-id: seataServer.properties
security:
  oauth2:
    client:
      #基操
      client-id: web
      client-secret: 654321
    resource:
      #因为资源服务器得验证你的Token是否有访问此资源的权限以及用户信息，所以只需要一个验证地址
      token-info-uri: http://localhost:8501/sso/oauth/check_token