server:
  port: 8101
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud
    username: root
    password: root
  # 应用名称
  application:
    name: userservice
#  session:
#    # 存储类型修改为redis
#    store-type: redis
#  redis:
#    # Redis服务器的信息
#    host: localhost
  cloud:
    nacos:
      discovery:
        #配置nacos注册中心地址
        server-addr: localhost:8848
        # 组别
        group: DEFAULT_GROUP
    sentinel:
      transport:
        # 添加监控页面地址即可
        dashboard: localhost:8858
seata:
  registry:
    type: nacos
    nacos:
      application: seata-server
      group: DEFAULT_GROUP
      server-addr: localhost:8848
      namespace: seata
  service:
    vgroup-mapping:
      default_tx_group: default
  #      bookservice_tx_group: default
  #  tx-service-group: 'bookservice_tx_group'
  config:
    type: nacos
    nacos:
      application: seata-server
      group: DEFAULT_GROUP
      server-addr: localhost:8848
      namespace: seata
      data-id: seataServer.properties
security:
  oauth2:
    client:
      #不多说了
      client-id: web
      client-secret: 654321
      #Token获取地址
      access-token-uri: http://localhost:8501/sso/oauth/token
      #验证页面地址
      user-authorization-uri: http://localhost:8501/sso/oauth/authorize
    resource:
      #Token信息获取和校验地址
      token-info-uri: http://localhost:8501/sso/oauth/check_token