server:
  port: 8101
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud
    username: root
    password: root
  # 应用名称
  application:
    name: userservice
  cloud:
    nacos:
      discovery:
        #配置nacos注册中心地址
        server-addr: localhost:8848
        # 组别
        group: DEFAULT_GROUP
    sentinel:
      transport:
        # 添加监控页面地址即可
        dashboard: localhost:8858
seata:
  registry:
    type: nacos
    nacos:
      application: seata-server
      group: DEFAULT_GROUP
      server-addr: localhost:8848
      namespace: seata
  service:
    vgroup-mapping:
      default_tx_group: default
  #      bookservice_tx_group: default
  #  tx-service-group: 'bookservice_tx_group'
  config:
    type: nacos
    nacos:
      application: seata-server
      group: DEFAULT_GROUP
      server-addr: localhost:8848
      namespace: seata
      data-id: seataServer.properties
